### ISSUE TITLE
Invalid argument supplied for foreach() 

### ISSUE THREAD

**Issue by msmolec** [themejack/fiera#1]
I'm a bit stuck, I keep getting this error. any help would be great :)
Warning: Invalid argument supplied for foreach() in C:\xampp\apps\wordpress\htdocs\wp-content\themes\fiera-master\inc\extras.php on line 77

function fiera_esc_buttons_data( $data = array() ) {
    $allowed_colors = array( 'red', 'blue', 'green', 'white', 'black', 'transparent' );

```
foreach ( $data as $key => $item ) {

    if ( empty( $item ) || ! isset( $item['link'] ) ) {
        unset( $data[ $key ] );
    }

    if ( isset( $item['title'] ) ) {
        $data[ $key ]['title'] = esc_html( $item['title'] );
    }

    $data[ $key ]['link'] = esc_url( $item['link'] );
    $data[ $key ]['color'] = isset( $item['color'] ) && in_array( $item['color'], $allowed_colors ) ? $item['color'] : $allowed_colors[0];
}

return $data;
```

}

**Comment by anteprimorac** [comment]
Fixed in release v1.0.1
