### ISSUE TITLE
Metaboxes.php bug

### ISSUE THREAD

**Issue by rachaelbelmas** [themejack/fiera#4]
Hi, tried installing Fiera 1.0.2 with Wordpress 4.6.1 and I got:

Warning: require(OmniBuilder/Builder.php): failed to open stream: No such file or directory in /home/public_html/wp-content/themes/fiera-1.0.2/inc/metaboxes.php on line 10

Warning: require(OmniBuilder/Builder.php): failed to open stream: No such file or directory in /home/public_html/wp-content/themes/fiera-1.0.2/inc/metaboxes.php on line 10

Fatal error: require(): Failed opening required 'OmniBuilder/Builder.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/public_html/wp-content/themes/fiera-1.0.2/inc/metaboxes.php on line 10

Help appreciated thank you!

**Comment by anteprimorac** [comment]
Hi @rachaelbelmas,
I assume that you downloaded .zip of master branch, but that file don't have OmniBuilder git submodule. That is how github work and we can not do anything about that file, but we created release files for each version of Fiera, so you can find each version in Release tab. Here is a direct link for Fiera v1.0.2 zip file - https://github.com/themejack/fiera/releases/download/v1.0.2/fiera-1.0.2.zip

Please, let me know if that works.

**Comment by rachaelbelmas** [comment]
it works thank you!
