### ISSUE TITLE
Template doesn't work - blank screen in frontend and admin

### ISSUE THREAD

**Issue by JBVeenstra** [themejack/fiera#5]
After installing the template in  a standard Wordpress 4.7.2, without any addition,  everything went blank. Theme is not working, even after I've replaced the files which were updated according to the fix info mentioned.
Help would be appreciated, cause I like to use this great theme very much
PHP Version 5.5.36 an mysql 5.0.11

**Comment by anteprimorac** [comment]
Hi @JBVeenstra,
I have just tested Fiera on WP 4.7.2 and PHP 5.5.x and it is working fine. Have you downloaded theme from https://github.com/themejack/fiera/releases ? If not please remove `fiera` folder from `wp-content/themes/` and unpack downloaded zip(or tar.gz) there.

Let me know if that works for you.

**Comment by JBVeenstra** [comment]
Great! This works :) I found your theme on https://slicejack.com/fiera-free-responsive-wordpress-theme-events/ and downloaded it also through this site. Maybe these links must be updated.
Thanks for your quick response!

**Comment by anteprimorac** [comment]
Yes, there were inconsistency with links. Sorry for that. In next release we will update `README.md` with more information how to get started. Let me know if you found any issue or if you want to leave a feedback.

**Comment by JBVeenstra** [comment]
Is there demo content available? Like the content of your demosite?

**Comment by anteprimorac** [comment]
Currently it is not available, but we are working on bringing "import demo content" functionality to all our themes.

**Comment by iamshaheen** [comment]
hey @anteprimorac ! i got the same problem not. everything went blank. Theme is not working

**Comment by luvmaloo** [comment]
After installing 1.0.2 latest version 'am getting a blank page. How do we get the demo content like yours?
