### ISSUE TITLE
Top menu bar transparent

### ISSUE THREAD

**Issue by P373** [themejack/fiera#8]
Great theme,
How do you make the top menu bar transparent? And how do you get the one-page effect when you add sections? Thanks

**Comment by anteprimorac** [comment]
Hi @P373 ,
probably you didn't set static page for front page. You can find instructions for that [here](https://codex.wordpress.org/Creating_a_Static_Front_Page#WordPress_Static_Front_Page_Process). After setting that option you will be able to add sections to front page. That will make menu bar transparent.
